Release workflow && Switch tests to using yarn
kiwiirc/irc-framework pull request #286
Opened 2021-06-07 16:22 UTC by ItsOnlyBinary

Looking at the existing npm packages I assume build is required as part of the release workflow.

2021-06-07 18:36 UTC, MaxLeiter requested changes

2021-06-07 18:36 UTC, MaxLeiter commented on .github/workflows/tests.yml
> +        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
Node 10 went EOL, can probably remove

2021-06-07 22:44 UTC, ItsOnlyBinary commented on .github/workflows/tests.yml
> +        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
good call ;) thanks

2021-06-08 03:39 UTC, MaxLeiter commented
not sure `npm-run-all` is necessary but that's a nitpick. Seems good

2021-06-08 03:39 UTC, MaxLeiter approved these changes

2021-06-22 15:20 UTC, merged