Only parse and emit whox requests that originated from irc-fw
kiwiirc/irc-framework pull request #333
Opened 2022-04-29 16:56 UTC by ItsOnlyBinary

2022-05-02 01:02 UTC, MaxLeiter requested changes

2022-05-02 01:02 UTC, MaxLeiter commented on src/helpers.js
> +    Object.defineProperty(unparsedFlags, 'hasThenRemove', {
I think `const hasThenRemove = (flag) =>  {...}` is easier to read

2022-05-02 17:12 UTC, ItsOnlyBinary commented on src/helpers.js
> +        flags.bot = unparsedFlags.hasThenRemove(bot_mode_token);
inspircd seems to add bot as a separate token, so in the refactor I've accounted for both possibilities

some examples from insp operator: `H*@s`, bot: `HsB`

2022-05-03 09:03 UTC, SadieCat commented on src/helpers.js
> +    parsedFlags.away = unparsedFlags.shift().toUpperCase() === 'G';
There is no guarantee that WHO flags will be in any specific order.

2022-05-03 09:07 UTC, SadieCat commented on src/commands/handlers/misc.js
> +        const op_level = !/^[0-9]+$/.test(params[10]) ? 0 : parseInt(params[10], 10);
Op levels aren't very well defined (and were implemented wrong in InspIRCd before 3.13.0) but according to the spec a lower op level means that the users rank is higher not lower.

2022-05-03 09:08 UTC, SadieCat commented on src/commands/handlers/misc.js
> +            const token = parseInt(params[1], 10) || 0;
You should probably also check if the WHOX response has enough parameters just in case someone accidentally reuses your token.

2022-09-08 03:58 UTC, MaxLeiter commented
@ItsOnlyBinary Is this ready?

2022-09-08 10:50 UTC, ItsOnlyBinary commented
I think so, guess i left it for other people to take a look over

2022-09-20 16:10 UTC, ItsOnlyBinary commented
@MaxLeiter could you please test this with thelounge just for my sanity, I would like to do a release including this.

2022-09-20 16:37 UTC, MaxLeiter commented
Sure thing, will do in the nexg ~day

2022-10-09 23:28 UTC, MaxLeiter commented
Well that was a long few days, but 👍

2022-10-09 23:28 UTC, MaxLeiter approved these changes

2022-10-11 11:38 UTC, merged